// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ContestRepository is an autogenerated mock type for the ContestRepository type
type ContestRepository struct {
	mock.Mock
}

type ContestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ContestRepository) EXPECT() *ContestRepository_Expecter {
	return &ContestRepository_Expecter{mock: &_m.Mock}
}

// ClaimSquare provides a mock function with given fields: ctx, square, value, owner, ownerName
func (_m *ContestRepository) ClaimSquare(ctx context.Context, square *model.Square, value string, owner string, ownerName string) (*model.Square, error) {
	ret := _m.Called(ctx, square, value, owner, ownerName)

	if len(ret) == 0 {
		panic("no return value specified for ClaimSquare")
	}

	var r0 *model.Square
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Square, string, string, string) (*model.Square, error)); ok {
		return rf(ctx, square, value, owner, ownerName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Square, string, string, string) *model.Square); ok {
		r0 = rf(ctx, square, value, owner, ownerName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Square)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Square, string, string, string) error); ok {
		r1 = rf(ctx, square, value, owner, ownerName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestRepository_ClaimSquare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimSquare'
type ContestRepository_ClaimSquare_Call struct {
	*mock.Call
}

// ClaimSquare is a helper method to define mock.On call
//   - ctx context.Context
//   - square *model.Square
//   - value string
//   - owner string
//   - ownerName string
func (_e *ContestRepository_Expecter) ClaimSquare(ctx interface{}, square interface{}, value interface{}, owner interface{}, ownerName interface{}) *ContestRepository_ClaimSquare_Call {
	return &ContestRepository_ClaimSquare_Call{Call: _e.mock.On("ClaimSquare", ctx, square, value, owner, ownerName)}
}

func (_c *ContestRepository_ClaimSquare_Call) Run(run func(ctx context.Context, square *model.Square, value string, owner string, ownerName string)) *ContestRepository_ClaimSquare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Square), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *ContestRepository_ClaimSquare_Call) Return(_a0 *model.Square, _a1 error) *ContestRepository_ClaimSquare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestRepository_ClaimSquare_Call) RunAndReturn(run func(context.Context, *model.Square, string, string, string) (*model.Square, error)) *ContestRepository_ClaimSquare_Call {
	_c.Call.Return(run)
	return _c
}

// ClearSquare provides a mock function with given fields: ctx, square
func (_m *ContestRepository) ClearSquare(ctx context.Context, square *model.Square) (*model.Square, error) {
	ret := _m.Called(ctx, square)

	if len(ret) == 0 {
		panic("no return value specified for ClearSquare")
	}

	var r0 *model.Square
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Square) (*model.Square, error)); ok {
		return rf(ctx, square)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Square) *model.Square); ok {
		r0 = rf(ctx, square)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Square)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Square) error); ok {
		r1 = rf(ctx, square)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestRepository_ClearSquare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSquare'
type ContestRepository_ClearSquare_Call struct {
	*mock.Call
}

// ClearSquare is a helper method to define mock.On call
//   - ctx context.Context
//   - square *model.Square
func (_e *ContestRepository_Expecter) ClearSquare(ctx interface{}, square interface{}) *ContestRepository_ClearSquare_Call {
	return &ContestRepository_ClearSquare_Call{Call: _e.mock.On("ClearSquare", ctx, square)}
}

func (_c *ContestRepository_ClearSquare_Call) Run(run func(ctx context.Context, square *model.Square)) *ContestRepository_ClearSquare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Square))
	})
	return _c
}

func (_c *ContestRepository_ClearSquare_Call) Return(_a0 *model.Square, _a1 error) *ContestRepository_ClearSquare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestRepository_ClearSquare_Call) RunAndReturn(run func(context.Context, *model.Square) (*model.Square, error)) *ContestRepository_ClearSquare_Call {
	_c.Call.Return(run)
	return _c
}

// ClearSquaresByOwner provides a mock function with given fields: ctx, contestID, owner
func (_m *ContestRepository) ClearSquaresByOwner(ctx context.Context, contestID uuid.UUID, owner string) ([]model.Square, error) {
	ret := _m.Called(ctx, contestID, owner)

	if len(ret) == 0 {
		panic("no return value specified for ClearSquaresByOwner")
	}

	var r0 []model.Square
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]model.Square, error)); ok {
		return rf(ctx, contestID, owner)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []model.Square); ok {
		r0 = rf(ctx, contestID, owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Square)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, contestID, owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestRepository_ClearSquaresByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSquaresByOwner'
type ContestRepository_ClearSquaresByOwner_Call struct {
	*mock.Call
}

// ClearSquaresByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - owner string
func (_e *ContestRepository_Expecter) ClearSquaresByOwner(ctx interface{}, contestID interface{}, owner interface{}) *ContestRepository_ClearSquaresByOwner_Call {
	return &ContestRepository_ClearSquaresByOwner_Call{Call: _e.mock.On("ClearSquaresByOwner", ctx, contestID, owner)}
}

func (_c *ContestRepository_ClearSquaresByOwner_Call) Run(run func(ctx context.Context, contestID uuid.UUID, owner string)) *ContestRepository_ClearSquaresByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ContestRepository_ClearSquaresByOwner_Call) Return(_a0 []model.Square, _a1 error) *ContestRepository_ClearSquaresByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestRepository_ClearSquaresByOwner_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) ([]model.Square, error)) *ContestRepository_ClearSquaresByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, contest, owner
func (_m *ContestRepository) Create(ctx context.Context, contest *model.Contest, owner *model.ContestParticipant) error {
	ret := _m.Called(ctx, contest, owner)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Contest, *model.ContestParticipant) error); ok {
		r0 = rf(ctx, contest, owner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContestRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ContestRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - contest *model.Contest
//   - owner *model.ContestParticipant
func (_e *ContestRepository_Expecter) Create(ctx interface{}, contest interface{}, owner interface{}) *ContestRepository_Create_Call {
	return &ContestRepository_Create_Call{Call: _e.mock.On("Create", ctx, contest, owner)}
}

func (_c *ContestRepository_Create_Call) Run(run func(ctx context.Context, contest *model.Contest, owner *model.ContestParticipant)) *ContestRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Contest), args[2].(*model.ContestParticipant))
	})
	return _c
}

func (_c *ContestRepository_Create_Call) Return(_a0 error) *ContestRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContestRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Contest, *model.ContestParticipant) error) *ContestRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateQuarterResult provides a mock function with given fields: ctx, result
func (_m *ContestRepository) CreateQuarterResult(ctx context.Context, result *model.QuarterResult) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuarterResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.QuarterResult) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContestRepository_CreateQuarterResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQuarterResult'
type ContestRepository_CreateQuarterResult_Call struct {
	*mock.Call
}

// CreateQuarterResult is a helper method to define mock.On call
//   - ctx context.Context
//   - result *model.QuarterResult
func (_e *ContestRepository_Expecter) CreateQuarterResult(ctx interface{}, result interface{}) *ContestRepository_CreateQuarterResult_Call {
	return &ContestRepository_CreateQuarterResult_Call{Call: _e.mock.On("CreateQuarterResult", ctx, result)}
}

func (_c *ContestRepository_CreateQuarterResult_Call) Run(run func(ctx context.Context, result *model.QuarterResult)) *ContestRepository_CreateQuarterResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.QuarterResult))
	})
	return _c
}

func (_c *ContestRepository_CreateQuarterResult_Call) Return(_a0 error) *ContestRepository_CreateQuarterResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContestRepository_CreateQuarterResult_Call) RunAndReturn(run func(context.Context, *model.QuarterResult) error) *ContestRepository_CreateQuarterResult_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ContestRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContestRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ContestRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ContestRepository_Expecter) Delete(ctx interface{}, id interface{}) *ContestRepository_Delete_Call {
	return &ContestRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ContestRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ContestRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ContestRepository_Delete_Call) Return(_a0 error) *ContestRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContestRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ContestRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByOwnerAndName provides a mock function with given fields: ctx, owner, name
func (_m *ContestRepository) ExistsByOwnerAndName(ctx context.Context, owner string, name string) (bool, error) {
	ret := _m.Called(ctx, owner, name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByOwnerAndName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, owner, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, owner, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, owner, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestRepository_ExistsByOwnerAndName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByOwnerAndName'
type ContestRepository_ExistsByOwnerAndName_Call struct {
	*mock.Call
}

// ExistsByOwnerAndName is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - name string
func (_e *ContestRepository_Expecter) ExistsByOwnerAndName(ctx interface{}, owner interface{}, name interface{}) *ContestRepository_ExistsByOwnerAndName_Call {
	return &ContestRepository_ExistsByOwnerAndName_Call{Call: _e.mock.On("ExistsByOwnerAndName", ctx, owner, name)}
}

func (_c *ContestRepository_ExistsByOwnerAndName_Call) Run(run func(ctx context.Context, owner string, name string)) *ContestRepository_ExistsByOwnerAndName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ContestRepository_ExistsByOwnerAndName_Call) Return(_a0 bool, _a1 error) *ContestRepository_ExistsByOwnerAndName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestRepository_ExistsByOwnerAndName_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *ContestRepository_ExistsByOwnerAndName_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByOwnerPaginated provides a mock function with given fields: ctx, owner, page, limit, search
func (_m *ContestRepository) GetAllByOwnerPaginated(ctx context.Context, owner string, page int, limit int, search string) ([]model.Contest, int64, error) {
	ret := _m.Called(ctx, owner, page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByOwnerPaginated")
	}

	var r0 []model.Contest
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) ([]model.Contest, int64, error)); ok {
		return rf(ctx, owner, page, limit, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) []model.Contest); ok {
		r0 = rf(ctx, owner, page, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Contest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, string) int64); ok {
		r1 = rf(ctx, owner, page, limit, search)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, string) error); ok {
		r2 = rf(ctx, owner, page, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ContestRepository_GetAllByOwnerPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByOwnerPaginated'
type ContestRepository_GetAllByOwnerPaginated_Call struct {
	*mock.Call
}

// GetAllByOwnerPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - page int
//   - limit int
//   - search string
func (_e *ContestRepository_Expecter) GetAllByOwnerPaginated(ctx interface{}, owner interface{}, page interface{}, limit interface{}, search interface{}) *ContestRepository_GetAllByOwnerPaginated_Call {
	return &ContestRepository_GetAllByOwnerPaginated_Call{Call: _e.mock.On("GetAllByOwnerPaginated", ctx, owner, page, limit, search)}
}

func (_c *ContestRepository_GetAllByOwnerPaginated_Call) Run(run func(ctx context.Context, owner string, page int, limit int, search string)) *ContestRepository_GetAllByOwnerPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *ContestRepository_GetAllByOwnerPaginated_Call) Return(_a0 []model.Contest, _a1 int64, _a2 error) *ContestRepository_GetAllByOwnerPaginated_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ContestRepository_GetAllByOwnerPaginated_Call) RunAndReturn(run func(context.Context, string, int, int, string) ([]model.Contest, int64, error)) *ContestRepository_GetAllByOwnerPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByParticipantUserID provides a mock function with given fields: ctx, userID, search
func (_m *ContestRepository) GetAllByParticipantUserID(ctx context.Context, userID string, search string) ([]model.Contest, error) {
	ret := _m.Called(ctx, userID, search)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByParticipantUserID")
	}

	var r0 []model.Contest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Contest, error)); ok {
		return rf(ctx, userID, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.Contest); ok {
		r0 = rf(ctx, userID, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Contest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestRepository_GetAllByParticipantUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByParticipantUserID'
type ContestRepository_GetAllByParticipantUserID_Call struct {
	*mock.Call
}

// GetAllByParticipantUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - search string
func (_e *ContestRepository_Expecter) GetAllByParticipantUserID(ctx interface{}, userID interface{}, search interface{}) *ContestRepository_GetAllByParticipantUserID_Call {
	return &ContestRepository_GetAllByParticipantUserID_Call{Call: _e.mock.On("GetAllByParticipantUserID", ctx, userID, search)}
}

func (_c *ContestRepository_GetAllByParticipantUserID_Call) Run(run func(ctx context.Context, userID string, search string)) *ContestRepository_GetAllByParticipantUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ContestRepository_GetAllByParticipantUserID_Call) Return(_a0 []model.Contest, _a1 error) *ContestRepository_GetAllByParticipantUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestRepository_GetAllByParticipantUserID_Call) RunAndReturn(run func(context.Context, string, string) ([]model.Contest, error)) *ContestRepository_GetAllByParticipantUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGameID provides a mock function with given fields: ctx, gameID
func (_m *ContestRepository) GetByGameID(ctx context.Context, gameID uuid.UUID) ([]model.Contest, error) {
	ret := _m.Called(ctx, gameID)

	if len(ret) == 0 {
		panic("no return value specified for GetByGameID")
	}

	var r0 []model.Contest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Contest, error)); ok {
		return rf(ctx, gameID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Contest); ok {
		r0 = rf(ctx, gameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Contest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestRepository_GetByGameID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGameID'
type ContestRepository_GetByGameID_Call struct {
	*mock.Call
}

// GetByGameID is a helper method to define mock.On call
//   - ctx context.Context
//   - gameID uuid.UUID
func (_e *ContestRepository_Expecter) GetByGameID(ctx interface{}, gameID interface{}) *ContestRepository_GetByGameID_Call {
	return &ContestRepository_GetByGameID_Call{Call: _e.mock.On("GetByGameID", ctx, gameID)}
}

func (_c *ContestRepository_GetByGameID_Call) Run(run func(ctx context.Context, gameID uuid.UUID)) *ContestRepository_GetByGameID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ContestRepository_GetByGameID_Call) Return(_a0 []model.Contest, _a1 error) *ContestRepository_GetByGameID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestRepository_GetByGameID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Contest, error)) *ContestRepository_GetByGameID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ContestRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Contest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Contest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Contest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Contest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Contest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ContestRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ContestRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ContestRepository_GetByID_Call {
	return &ContestRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ContestRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ContestRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ContestRepository_GetByID_Call) Return(_a0 *model.Contest, _a1 error) *ContestRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Contest, error)) *ContestRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetVisibilityByID provides a mock function with given fields: ctx, id
func (_m *ContestRepository) GetVisibilityByID(ctx context.Context, id uuid.UUID) (model.ContestVisibility, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVisibilityByID")
	}

	var r0 model.ContestVisibility
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.ContestVisibility, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.ContestVisibility); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.ContestVisibility)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestRepository_GetVisibilityByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVisibilityByID'
type ContestRepository_GetVisibilityByID_Call struct {
	*mock.Call
}

// GetVisibilityByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ContestRepository_Expecter) GetVisibilityByID(ctx interface{}, id interface{}) *ContestRepository_GetVisibilityByID_Call {
	return &ContestRepository_GetVisibilityByID_Call{Call: _e.mock.On("GetVisibilityByID", ctx, id)}
}

func (_c *ContestRepository_GetVisibilityByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ContestRepository_GetVisibilityByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ContestRepository_GetVisibilityByID_Call) Return(_a0 model.ContestVisibility, _a1 error) *ContestRepository_GetVisibilityByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestRepository_GetVisibilityByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.ContestVisibility, error)) *ContestRepository_GetVisibilityByID_Call {
	_c.Call.Return(run)
	return _c
}

// GhostSquare provides a mock function with given fields: ctx, square
func (_m *ContestRepository) GhostSquare(ctx context.Context, square *model.Square) (*model.Square, error) {
	ret := _m.Called(ctx, square)

	if len(ret) == 0 {
		panic("no return value specified for GhostSquare")
	}

	var r0 *model.Square
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Square) (*model.Square, error)); ok {
		return rf(ctx, square)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Square) *model.Square); ok {
		r0 = rf(ctx, square)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Square)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Square) error); ok {
		r1 = rf(ctx, square)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestRepository_GhostSquare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GhostSquare'
type ContestRepository_GhostSquare_Call struct {
	*mock.Call
}

// GhostSquare is a helper method to define mock.On call
//   - ctx context.Context
//   - square *model.Square
func (_e *ContestRepository_Expecter) GhostSquare(ctx interface{}, square interface{}) *ContestRepository_GhostSquare_Call {
	return &ContestRepository_GhostSquare_Call{Call: _e.mock.On("GhostSquare", ctx, square)}
}

func (_c *ContestRepository_GhostSquare_Call) Run(run func(ctx context.Context, square *model.Square)) *ContestRepository_GhostSquare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Square))
	})
	return _c
}

func (_c *ContestRepository_GhostSquare_Call) Return(_a0 *model.Square, _a1 error) *ContestRepository_GhostSquare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestRepository_GhostSquare_Call) RunAndReturn(run func(context.Context, *model.Square) (*model.Square, error)) *ContestRepository_GhostSquare_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackQuarterResult provides a mock function with given fields: ctx, resultID, contest
func (_m *ContestRepository) RollbackQuarterResult(ctx context.Context, resultID uuid.UUID, contest *model.Contest) error {
	ret := _m.Called(ctx, resultID, contest)

	if len(ret) == 0 {
		panic("no return value specified for RollbackQuarterResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.Contest) error); ok {
		r0 = rf(ctx, resultID, contest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContestRepository_RollbackQuarterResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackQuarterResult'
type ContestRepository_RollbackQuarterResult_Call struct {
	*mock.Call
}

// RollbackQuarterResult is a helper method to define mock.On call
//   - ctx context.Context
//   - resultID uuid.UUID
//   - contest *model.Contest
func (_e *ContestRepository_Expecter) RollbackQuarterResult(ctx interface{}, resultID interface{}, contest interface{}) *ContestRepository_RollbackQuarterResult_Call {
	return &ContestRepository_RollbackQuarterResult_Call{Call: _e.mock.On("RollbackQuarterResult", ctx, resultID, contest)}
}

func (_c *ContestRepository_RollbackQuarterResult_Call) Run(run func(ctx context.Context, resultID uuid.UUID, contest *model.Contest)) *ContestRepository_RollbackQuarterResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*model.Contest))
	})
	return _c
}

func (_c *ContestRepository_RollbackQuarterResult_Call) Return(_a0 error) *ContestRepository_RollbackQuarterResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContestRepository_RollbackQuarterResult_Call) RunAndReturn(run func(context.Context, uuid.UUID, *model.Contest) error) *ContestRepository_RollbackQuarterResult_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, contest
func (_m *ContestRepository) Update(ctx context.Context, contest *model.Contest) error {
	ret := _m.Called(ctx, contest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Contest) error); ok {
		r0 = rf(ctx, contest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContestRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ContestRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - contest *model.Contest
func (_e *ContestRepository_Expecter) Update(ctx interface{}, contest interface{}) *ContestRepository_Update_Call {
	return &ContestRepository_Update_Call{Call: _e.mock.On("Update", ctx, contest)}
}

func (_c *ContestRepository_Update_Call) Run(run func(ctx context.Context, contest *model.Contest)) *ContestRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Contest))
	})
	return _c
}

func (_c *ContestRepository_Update_Call) Return(_a0 error) *ContestRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContestRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Contest) error) *ContestRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewContestRepository creates a new instance of ContestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContestRepository {
	mock := &ContestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
