// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ContactRepository is an autogenerated mock type for the ContactRepository type
type ContactRepository struct {
	mock.Mock
}

type ContactRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ContactRepository) EXPECT() *ContactRepository_Expecter {
	return &ContactRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, submission
func (_m *ContactRepository) Create(ctx context.Context, submission *model.ContactSubmission) error {
	ret := _m.Called(ctx, submission)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ContactSubmission) error); ok {
		r0 = rf(ctx, submission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContactRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ContactRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - submission *model.ContactSubmission
func (_e *ContactRepository_Expecter) Create(ctx interface{}, submission interface{}) *ContactRepository_Create_Call {
	return &ContactRepository_Create_Call{Call: _e.mock.On("Create", ctx, submission)}
}

func (_c *ContactRepository_Create_Call) Run(run func(ctx context.Context, submission *model.ContactSubmission)) *ContactRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.ContactSubmission))
	})
	return _c
}

func (_c *ContactRepository_Create_Call) Return(_a0 error) *ContactRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContactRepository_Create_Call) RunAndReturn(run func(context.Context, *model.ContactSubmission) error) *ContactRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewContactRepository creates a new instance of ContactRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContactRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContactRepository {
	mock := &ContactRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
