// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ContactService is an autogenerated mock type for the ContactService type
type ContactService struct {
	mock.Mock
}

type ContactService_Expecter struct {
	mock *mock.Mock
}

func (_m *ContactService) EXPECT() *ContactService_Expecter {
	return &ContactService_Expecter{mock: &_m.Mock}
}

// SubmitContact provides a mock function with given fields: ctx, req, ipAddress
func (_m *ContactService) SubmitContact(ctx context.Context, req *model.ContactRequest, ipAddress string) error {
	ret := _m.Called(ctx, req, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for SubmitContact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ContactRequest, string) error); ok {
		r0 = rf(ctx, req, ipAddress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContactService_SubmitContact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitContact'
type ContactService_SubmitContact_Call struct {
	*mock.Call
}

// SubmitContact is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.ContactRequest
//   - ipAddress string
func (_e *ContactService_Expecter) SubmitContact(ctx interface{}, req interface{}, ipAddress interface{}) *ContactService_SubmitContact_Call {
	return &ContactService_SubmitContact_Call{Call: _e.mock.On("SubmitContact", ctx, req, ipAddress)}
}

func (_c *ContactService_SubmitContact_Call) Run(run func(ctx context.Context, req *model.ContactRequest, ipAddress string)) *ContactService_SubmitContact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.ContactRequest), args[2].(string))
	})
	return _c
}

func (_c *ContactService_SubmitContact_Call) Return(_a0 error) *ContactService_SubmitContact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContactService_SubmitContact_Call) RunAndReturn(run func(context.Context, *model.ContactRequest, string) error) *ContactService_SubmitContact_Call {
	_c.Call.Return(run)
	return _c
}

// NewContactService creates a new instance of ContactService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContactService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContactService {
	mock := &ContactService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
