// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ContestService is an autogenerated mock type for the ContestService type
type ContestService struct {
	mock.Mock
}

type ContestService_Expecter struct {
	mock *mock.Mock
}

func (_m *ContestService) EXPECT() *ContestService_Expecter {
	return &ContestService_Expecter{mock: &_m.Mock}
}

// ClearSquare provides a mock function with given fields: ctx, contestID, squareID, user
func (_m *ContestService) ClearSquare(ctx context.Context, contestID uuid.UUID, squareID uuid.UUID, user string) (*model.Square, error) {
	ret := _m.Called(ctx, contestID, squareID, user)

	if len(ret) == 0 {
		panic("no return value specified for ClearSquare")
	}

	var r0 *model.Square
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*model.Square, error)); ok {
		return rf(ctx, contestID, squareID, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *model.Square); ok {
		r0 = rf(ctx, contestID, squareID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Square)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, contestID, squareID, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestService_ClearSquare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSquare'
type ContestService_ClearSquare_Call struct {
	*mock.Call
}

// ClearSquare is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - squareID uuid.UUID
//   - user string
func (_e *ContestService_Expecter) ClearSquare(ctx interface{}, contestID interface{}, squareID interface{}, user interface{}) *ContestService_ClearSquare_Call {
	return &ContestService_ClearSquare_Call{Call: _e.mock.On("ClearSquare", ctx, contestID, squareID, user)}
}

func (_c *ContestService_ClearSquare_Call) Run(run func(ctx context.Context, contestID uuid.UUID, squareID uuid.UUID, user string)) *ContestService_ClearSquare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *ContestService_ClearSquare_Call) Return(_a0 *model.Square, _a1 error) *ContestService_ClearSquare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestService_ClearSquare_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (*model.Square, error)) *ContestService_ClearSquare_Call {
	_c.Call.Return(run)
	return _c
}

// CreateContest provides a mock function with given fields: ctx, req, user
func (_m *ContestService) CreateContest(ctx context.Context, req *model.CreateContestRequest, user string) (*model.Contest, error) {
	ret := _m.Called(ctx, req, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateContest")
	}

	var r0 *model.Contest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateContestRequest, string) (*model.Contest, error)); ok {
		return rf(ctx, req, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateContestRequest, string) *model.Contest); ok {
		r0 = rf(ctx, req, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Contest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateContestRequest, string) error); ok {
		r1 = rf(ctx, req, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestService_CreateContest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateContest'
type ContestService_CreateContest_Call struct {
	*mock.Call
}

// CreateContest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.CreateContestRequest
//   - user string
func (_e *ContestService_Expecter) CreateContest(ctx interface{}, req interface{}, user interface{}) *ContestService_CreateContest_Call {
	return &ContestService_CreateContest_Call{Call: _e.mock.On("CreateContest", ctx, req, user)}
}

func (_c *ContestService_CreateContest_Call) Run(run func(ctx context.Context, req *model.CreateContestRequest, user string)) *ContestService_CreateContest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.CreateContestRequest), args[2].(string))
	})
	return _c
}

func (_c *ContestService_CreateContest_Call) Return(_a0 *model.Contest, _a1 error) *ContestService_CreateContest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestService_CreateContest_Call) RunAndReturn(run func(context.Context, *model.CreateContestRequest, string) (*model.Contest, error)) *ContestService_CreateContest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteContest provides a mock function with given fields: ctx, contestID, user
func (_m *ContestService) DeleteContest(ctx context.Context, contestID uuid.UUID, user string) error {
	ret := _m.Called(ctx, contestID, user)

	if len(ret) == 0 {
		panic("no return value specified for DeleteContest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, contestID, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContestService_DeleteContest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteContest'
type ContestService_DeleteContest_Call struct {
	*mock.Call
}

// DeleteContest is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - user string
func (_e *ContestService_Expecter) DeleteContest(ctx interface{}, contestID interface{}, user interface{}) *ContestService_DeleteContest_Call {
	return &ContestService_DeleteContest_Call{Call: _e.mock.On("DeleteContest", ctx, contestID, user)}
}

func (_c *ContestService_DeleteContest_Call) Run(run func(ctx context.Context, contestID uuid.UUID, user string)) *ContestService_DeleteContest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ContestService_DeleteContest_Call) Return(_a0 error) *ContestService_DeleteContest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContestService_DeleteContest_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *ContestService_DeleteContest_Call {
	_c.Call.Return(run)
	return _c
}

// GetContestsByOwnerPaginated provides a mock function with given fields: ctx, owner, page, limit, search
func (_m *ContestService) GetContestsByOwnerPaginated(ctx context.Context, owner string, page int, limit int, search string) ([]model.Contest, int64, error) {
	ret := _m.Called(ctx, owner, page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for GetContestsByOwnerPaginated")
	}

	var r0 []model.Contest
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) ([]model.Contest, int64, error)); ok {
		return rf(ctx, owner, page, limit, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) []model.Contest); ok {
		r0 = rf(ctx, owner, page, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Contest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, string) int64); ok {
		r1 = rf(ctx, owner, page, limit, search)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, string) error); ok {
		r2 = rf(ctx, owner, page, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ContestService_GetContestsByOwnerPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContestsByOwnerPaginated'
type ContestService_GetContestsByOwnerPaginated_Call struct {
	*mock.Call
}

// GetContestsByOwnerPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - page int
//   - limit int
//   - search string
func (_e *ContestService_Expecter) GetContestsByOwnerPaginated(ctx interface{}, owner interface{}, page interface{}, limit interface{}, search interface{}) *ContestService_GetContestsByOwnerPaginated_Call {
	return &ContestService_GetContestsByOwnerPaginated_Call{Call: _e.mock.On("GetContestsByOwnerPaginated", ctx, owner, page, limit, search)}
}

func (_c *ContestService_GetContestsByOwnerPaginated_Call) Run(run func(ctx context.Context, owner string, page int, limit int, search string)) *ContestService_GetContestsByOwnerPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *ContestService_GetContestsByOwnerPaginated_Call) Return(_a0 []model.Contest, _a1 int64, _a2 error) *ContestService_GetContestsByOwnerPaginated_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ContestService_GetContestsByOwnerPaginated_Call) RunAndReturn(run func(context.Context, string, int, int, string) ([]model.Contest, int64, error)) *ContestService_GetContestsByOwnerPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// RecordQuarterResult provides a mock function with given fields: ctx, contestID, homeScore, awayScore, user
func (_m *ContestService) RecordQuarterResult(ctx context.Context, contestID uuid.UUID, homeScore int, awayScore int, user string) (*model.QuarterResult, error) {
	ret := _m.Called(ctx, contestID, homeScore, awayScore, user)

	if len(ret) == 0 {
		panic("no return value specified for RecordQuarterResult")
	}

	var r0 *model.QuarterResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string) (*model.QuarterResult, error)); ok {
		return rf(ctx, contestID, homeScore, awayScore, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, string) *model.QuarterResult); ok {
		r0 = rf(ctx, contestID, homeScore, awayScore, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.QuarterResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int, string) error); ok {
		r1 = rf(ctx, contestID, homeScore, awayScore, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestService_RecordQuarterResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordQuarterResult'
type ContestService_RecordQuarterResult_Call struct {
	*mock.Call
}

// RecordQuarterResult is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - homeScore int
//   - awayScore int
//   - user string
func (_e *ContestService_Expecter) RecordQuarterResult(ctx interface{}, contestID interface{}, homeScore interface{}, awayScore interface{}, user interface{}) *ContestService_RecordQuarterResult_Call {
	return &ContestService_RecordQuarterResult_Call{Call: _e.mock.On("RecordQuarterResult", ctx, contestID, homeScore, awayScore, user)}
}

func (_c *ContestService_RecordQuarterResult_Call) Run(run func(ctx context.Context, contestID uuid.UUID, homeScore int, awayScore int, user string)) *ContestService_RecordQuarterResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *ContestService_RecordQuarterResult_Call) Return(_a0 *model.QuarterResult, _a1 error) *ContestService_RecordQuarterResult_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestService_RecordQuarterResult_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int, string) (*model.QuarterResult, error)) *ContestService_RecordQuarterResult_Call {
	_c.Call.Return(run)
	return _c
}

// StartContest provides a mock function with given fields: ctx, contestID, user
func (_m *ContestService) StartContest(ctx context.Context, contestID uuid.UUID, user string) (*model.Contest, error) {
	ret := _m.Called(ctx, contestID, user)

	if len(ret) == 0 {
		panic("no return value specified for StartContest")
	}

	var r0 *model.Contest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.Contest, error)); ok {
		return rf(ctx, contestID, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.Contest); ok {
		r0 = rf(ctx, contestID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Contest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, contestID, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestService_StartContest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContest'
type ContestService_StartContest_Call struct {
	*mock.Call
}

// StartContest is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - user string
func (_e *ContestService_Expecter) StartContest(ctx interface{}, contestID interface{}, user interface{}) *ContestService_StartContest_Call {
	return &ContestService_StartContest_Call{Call: _e.mock.On("StartContest", ctx, contestID, user)}
}

func (_c *ContestService_StartContest_Call) Run(run func(ctx context.Context, contestID uuid.UUID, user string)) *ContestService_StartContest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ContestService_StartContest_Call) Return(_a0 *model.Contest, _a1 error) *ContestService_StartContest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestService_StartContest_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*model.Contest, error)) *ContestService_StartContest_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateContest provides a mock function with given fields: ctx, contestID, req, user
func (_m *ContestService) UpdateContest(ctx context.Context, contestID uuid.UUID, req *model.UpdateContestRequest, user string) (*model.Contest, error) {
	ret := _m.Called(ctx, contestID, req, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateContest")
	}

	var r0 *model.Contest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdateContestRequest, string) (*model.Contest, error)); ok {
		return rf(ctx, contestID, req, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdateContestRequest, string) *model.Contest); ok {
		r0 = rf(ctx, contestID, req, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Contest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.UpdateContestRequest, string) error); ok {
		r1 = rf(ctx, contestID, req, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestService_UpdateContest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateContest'
type ContestService_UpdateContest_Call struct {
	*mock.Call
}

// UpdateContest is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - req *model.UpdateContestRequest
//   - user string
func (_e *ContestService_Expecter) UpdateContest(ctx interface{}, contestID interface{}, req interface{}, user interface{}) *ContestService_UpdateContest_Call {
	return &ContestService_UpdateContest_Call{Call: _e.mock.On("UpdateContest", ctx, contestID, req, user)}
}

func (_c *ContestService_UpdateContest_Call) Run(run func(ctx context.Context, contestID uuid.UUID, req *model.UpdateContestRequest, user string)) *ContestService_UpdateContest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*model.UpdateContestRequest), args[3].(string))
	})
	return _c
}

func (_c *ContestService_UpdateContest_Call) Return(_a0 *model.Contest, _a1 error) *ContestService_UpdateContest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestService_UpdateContest_Call) RunAndReturn(run func(context.Context, uuid.UUID, *model.UpdateContestRequest, string) (*model.Contest, error)) *ContestService_UpdateContest_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSquare provides a mock function with given fields: ctx, contestID, squareID, req, user
func (_m *ContestService) UpdateSquare(ctx context.Context, contestID uuid.UUID, squareID uuid.UUID, req *model.UpdateSquareRequest, user string) (*model.Square, error) {
	ret := _m.Called(ctx, contestID, squareID, req, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSquare")
	}

	var r0 *model.Square
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.UpdateSquareRequest, string) (*model.Square, error)); ok {
		return rf(ctx, contestID, squareID, req, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.UpdateSquareRequest, string) *model.Square); ok {
		r0 = rf(ctx, contestID, squareID, req, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Square)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *model.UpdateSquareRequest, string) error); ok {
		r1 = rf(ctx, contestID, squareID, req, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContestService_UpdateSquare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSquare'
type ContestService_UpdateSquare_Call struct {
	*mock.Call
}

// UpdateSquare is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - squareID uuid.UUID
//   - req *model.UpdateSquareRequest
//   - user string
func (_e *ContestService_Expecter) UpdateSquare(ctx interface{}, contestID interface{}, squareID interface{}, req interface{}, user interface{}) *ContestService_UpdateSquare_Call {
	return &ContestService_UpdateSquare_Call{Call: _e.mock.On("UpdateSquare", ctx, contestID, squareID, req, user)}
}

func (_c *ContestService_UpdateSquare_Call) Run(run func(ctx context.Context, contestID uuid.UUID, squareID uuid.UUID, req *model.UpdateSquareRequest, user string)) *ContestService_UpdateSquare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*model.UpdateSquareRequest), args[4].(string))
	})
	return _c
}

func (_c *ContestService_UpdateSquare_Call) Return(_a0 *model.Square, _a1 error) *ContestService_UpdateSquare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContestService_UpdateSquare_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *model.UpdateSquareRequest, string) (*model.Square, error)) *ContestService_UpdateSquare_Call {
	_c.Call.Return(run)
	return _c
}

// NewContestService creates a new instance of ContestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContestService {
	mock := &ContestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
