// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ESPNClient is an autogenerated mock type for the ESPNClient type
type ESPNClient struct {
	mock.Mock
}

type ESPNClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ESPNClient) EXPECT() *ESPNClient_Expecter {
	return &ESPNClient_Expecter{mock: &_m.Mock}
}

// FetchScoreboard provides a mock function with given fields: ctx, dates
func (_m *ESPNClient) FetchScoreboard(ctx context.Context, dates string) ([]model.ESPNGame, error) {
	ret := _m.Called(ctx, dates)

	if len(ret) == 0 {
		panic("no return value specified for FetchScoreboard")
	}

	var r0 []model.ESPNGame
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.ESPNGame, error)); ok {
		return rf(ctx, dates)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.ESPNGame); ok {
		r0 = rf(ctx, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ESPNGame)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ESPNClient_FetchScoreboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchScoreboard'
type ESPNClient_FetchScoreboard_Call struct {
	*mock.Call
}

// FetchScoreboard is a helper method to define mock.On call
//   - ctx context.Context
//   - dates string
func (_e *ESPNClient_Expecter) FetchScoreboard(ctx interface{}, dates interface{}) *ESPNClient_FetchScoreboard_Call {
	return &ESPNClient_FetchScoreboard_Call{Call: _e.mock.On("FetchScoreboard", ctx, dates)}
}

func (_c *ESPNClient_FetchScoreboard_Call) Run(run func(ctx context.Context, dates string)) *ESPNClient_FetchScoreboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ESPNClient_FetchScoreboard_Call) Return(_a0 []model.ESPNGame, _a1 error) *ESPNClient_FetchScoreboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ESPNClient_FetchScoreboard_Call) RunAndReturn(run func(context.Context, string) ([]model.ESPNGame, error)) *ESPNClient_FetchScoreboard_Call {
	_c.Call.Return(run)
	return _c
}

// NewESPNClient creates a new instance of ESPNClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewESPNClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ESPNClient {
	mock := &ESPNClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
