// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GameRepository is an autogenerated mock type for the GameRepository type
type GameRepository struct {
	mock.Mock
}

type GameRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GameRepository) EXPECT() *GameRepository_Expecter {
	return &GameRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *GameRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Game, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Game, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Game); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type GameRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *GameRepository_Expecter) GetByID(ctx interface{}, id interface{}) *GameRepository_GetByID_Call {
	return &GameRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *GameRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *GameRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GameRepository_GetByID_Call) Return(_a0 *model.Game, _a1 error) *GameRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Game, error)) *GameRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpcoming provides a mock function with given fields: ctx
func (_m *GameRepository) GetUpcoming(ctx context.Context) ([]model.Game, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUpcoming")
	}

	var r0 []model.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Game, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Game); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameRepository_GetUpcoming_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpcoming'
type GameRepository_GetUpcoming_Call struct {
	*mock.Call
}

// GetUpcoming is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GameRepository_Expecter) GetUpcoming(ctx interface{}) *GameRepository_GetUpcoming_Call {
	return &GameRepository_GetUpcoming_Call{Call: _e.mock.On("GetUpcoming", ctx)}
}

func (_c *GameRepository_GetUpcoming_Call) Run(run func(ctx context.Context)) *GameRepository_GetUpcoming_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GameRepository_GetUpcoming_Call) Return(_a0 []model.Game, _a1 error) *GameRepository_GetUpcoming_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameRepository_GetUpcoming_Call) RunAndReturn(run func(context.Context) ([]model.Game, error)) *GameRepository_GetUpcoming_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, game
func (_m *GameRepository) Upsert(ctx context.Context, game *model.Game) error {
	ret := _m.Called(ctx, game)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Game) error); ok {
		r0 = rf(ctx, game)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GameRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type GameRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - game *model.Game
func (_e *GameRepository_Expecter) Upsert(ctx interface{}, game interface{}) *GameRepository_Upsert_Call {
	return &GameRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, game)}
}

func (_c *GameRepository_Upsert_Call) Run(run func(ctx context.Context, game *model.Game)) *GameRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Game))
	})
	return _c
}

func (_c *GameRepository_Upsert_Call) Return(_a0 error) *GameRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GameRepository_Upsert_Call) RunAndReturn(run func(context.Context, *model.Game) error) *GameRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertScore provides a mock function with given fields: ctx, score
func (_m *GameRepository) UpsertScore(ctx context.Context, score *model.GameScore) (bool, error) {
	ret := _m.Called(ctx, score)

	if len(ret) == 0 {
		panic("no return value specified for UpsertScore")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.GameScore) (bool, error)); ok {
		return rf(ctx, score)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.GameScore) bool); ok {
		r0 = rf(ctx, score)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.GameScore) error); ok {
		r1 = rf(ctx, score)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameRepository_UpsertScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertScore'
type GameRepository_UpsertScore_Call struct {
	*mock.Call
}

// UpsertScore is a helper method to define mock.On call
//   - ctx context.Context
//   - score *model.GameScore
func (_e *GameRepository_Expecter) UpsertScore(ctx interface{}, score interface{}) *GameRepository_UpsertScore_Call {
	return &GameRepository_UpsertScore_Call{Call: _e.mock.On("UpsertScore", ctx, score)}
}

func (_c *GameRepository_UpsertScore_Call) Run(run func(ctx context.Context, score *model.GameScore)) *GameRepository_UpsertScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.GameScore))
	})
	return _c
}

func (_c *GameRepository_UpsertScore_Call) Return(created bool, err error) *GameRepository_UpsertScore_Call {
	_c.Call.Return(created, err)
	return _c
}

func (_c *GameRepository_UpsertScore_Call) RunAndReturn(run func(context.Context, *model.GameScore) (bool, error)) *GameRepository_UpsertScore_Call {
	_c.Call.Return(run)
	return _c
}

// NewGameRepository creates a new instance of GameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GameRepository {
	mock := &GameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
