// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// InviteRepository is an autogenerated mock type for the InviteRepository type
type InviteRepository struct {
	mock.Mock
}

type InviteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InviteRepository) EXPECT() *InviteRepository_Expecter {
	return &InviteRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, invite
func (_m *InviteRepository) Create(ctx context.Context, invite *model.ContestInvite) error {
	ret := _m.Called(ctx, invite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ContestInvite) error); ok {
		r0 = rf(ctx, invite)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InviteRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type InviteRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - invite *model.ContestInvite
func (_e *InviteRepository_Expecter) Create(ctx interface{}, invite interface{}) *InviteRepository_Create_Call {
	return &InviteRepository_Create_Call{Call: _e.mock.On("Create", ctx, invite)}
}

func (_c *InviteRepository_Create_Call) Run(run func(ctx context.Context, invite *model.ContestInvite)) *InviteRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.ContestInvite))
	})
	return _c
}

func (_c *InviteRepository_Create_Call) Return(_a0 error) *InviteRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InviteRepository_Create_Call) RunAndReturn(run func(context.Context, *model.ContestInvite) error) *InviteRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *InviteRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InviteRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type InviteRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *InviteRepository_Expecter) Delete(ctx interface{}, id interface{}) *InviteRepository_Delete_Call {
	return &InviteRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *InviteRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *InviteRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *InviteRepository_Delete_Call) Return(_a0 error) *InviteRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InviteRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *InviteRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByContestID provides a mock function with given fields: ctx, contestID
func (_m *InviteRepository) GetAllByContestID(ctx context.Context, contestID uuid.UUID) ([]model.ContestInvite, error) {
	ret := _m.Called(ctx, contestID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByContestID")
	}

	var r0 []model.ContestInvite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ContestInvite, error)); ok {
		return rf(ctx, contestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.ContestInvite); ok {
		r0 = rf(ctx, contestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ContestInvite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, contestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteRepository_GetAllByContestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByContestID'
type InviteRepository_GetAllByContestID_Call struct {
	*mock.Call
}

// GetAllByContestID is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
func (_e *InviteRepository_Expecter) GetAllByContestID(ctx interface{}, contestID interface{}) *InviteRepository_GetAllByContestID_Call {
	return &InviteRepository_GetAllByContestID_Call{Call: _e.mock.On("GetAllByContestID", ctx, contestID)}
}

func (_c *InviteRepository_GetAllByContestID_Call) Run(run func(ctx context.Context, contestID uuid.UUID)) *InviteRepository_GetAllByContestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *InviteRepository_GetAllByContestID_Call) Return(_a0 []model.ContestInvite, _a1 error) *InviteRepository_GetAllByContestID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InviteRepository_GetAllByContestID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.ContestInvite, error)) *InviteRepository_GetAllByContestID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByToken provides a mock function with given fields: ctx, token
func (_m *InviteRepository) GetByToken(ctx context.Context, token string) (*model.ContestInvite, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetByToken")
	}

	var r0 *model.ContestInvite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.ContestInvite, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.ContestInvite); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ContestInvite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteRepository_GetByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByToken'
type InviteRepository_GetByToken_Call struct {
	*mock.Call
}

// GetByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *InviteRepository_Expecter) GetByToken(ctx interface{}, token interface{}) *InviteRepository_GetByToken_Call {
	return &InviteRepository_GetByToken_Call{Call: _e.mock.On("GetByToken", ctx, token)}
}

func (_c *InviteRepository_GetByToken_Call) Run(run func(ctx context.Context, token string)) *InviteRepository_GetByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InviteRepository_GetByToken_Call) Return(_a0 *model.ContestInvite, _a1 error) *InviteRepository_GetByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InviteRepository_GetByToken_Call) RunAndReturn(run func(context.Context, string) (*model.ContestInvite, error)) *InviteRepository_GetByToken_Call {
	_c.Call.Return(run)
	return _c
}

// RedeemInvite provides a mock function with given fields: ctx, inviteID, participant
func (_m *InviteRepository) RedeemInvite(ctx context.Context, inviteID uuid.UUID, participant *model.ContestParticipant) error {
	ret := _m.Called(ctx, inviteID, participant)

	if len(ret) == 0 {
		panic("no return value specified for RedeemInvite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.ContestParticipant) error); ok {
		r0 = rf(ctx, inviteID, participant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InviteRepository_RedeemInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RedeemInvite'
type InviteRepository_RedeemInvite_Call struct {
	*mock.Call
}

// RedeemInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - inviteID uuid.UUID
//   - participant *model.ContestParticipant
func (_e *InviteRepository_Expecter) RedeemInvite(ctx interface{}, inviteID interface{}, participant interface{}) *InviteRepository_RedeemInvite_Call {
	return &InviteRepository_RedeemInvite_Call{Call: _e.mock.On("RedeemInvite", ctx, inviteID, participant)}
}

func (_c *InviteRepository_RedeemInvite_Call) Run(run func(ctx context.Context, inviteID uuid.UUID, participant *model.ContestParticipant)) *InviteRepository_RedeemInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*model.ContestParticipant))
	})
	return _c
}

func (_c *InviteRepository_RedeemInvite_Call) Return(_a0 error) *InviteRepository_RedeemInvite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InviteRepository_RedeemInvite_Call) RunAndReturn(run func(context.Context, uuid.UUID, *model.ContestParticipant) error) *InviteRepository_RedeemInvite_Call {
	_c.Call.Return(run)
	return _c
}

// NewInviteRepository creates a new instance of InviteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteRepository {
	mock := &InviteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
