// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// InviteService is an autogenerated mock type for the InviteService type
type InviteService struct {
	mock.Mock
}

type InviteService_Expecter struct {
	mock *mock.Mock
}

func (_m *InviteService) EXPECT() *InviteService_Expecter {
	return &InviteService_Expecter{mock: &_m.Mock}
}

// CreateInvite provides a mock function with given fields: ctx, contestID, req, user
func (_m *InviteService) CreateInvite(ctx context.Context, contestID uuid.UUID, req *model.CreateInviteRequest, user string) (*model.ContestInvite, error) {
	ret := _m.Called(ctx, contestID, req, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvite")
	}

	var r0 *model.ContestInvite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.CreateInviteRequest, string) (*model.ContestInvite, error)); ok {
		return rf(ctx, contestID, req, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.CreateInviteRequest, string) *model.ContestInvite); ok {
		r0 = rf(ctx, contestID, req, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ContestInvite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.CreateInviteRequest, string) error); ok {
		r1 = rf(ctx, contestID, req, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteService_CreateInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvite'
type InviteService_CreateInvite_Call struct {
	*mock.Call
}

// CreateInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - req *model.CreateInviteRequest
//   - user string
func (_e *InviteService_Expecter) CreateInvite(ctx interface{}, contestID interface{}, req interface{}, user interface{}) *InviteService_CreateInvite_Call {
	return &InviteService_CreateInvite_Call{Call: _e.mock.On("CreateInvite", ctx, contestID, req, user)}
}

func (_c *InviteService_CreateInvite_Call) Run(run func(ctx context.Context, contestID uuid.UUID, req *model.CreateInviteRequest, user string)) *InviteService_CreateInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*model.CreateInviteRequest), args[3].(string))
	})
	return _c
}

func (_c *InviteService_CreateInvite_Call) Return(_a0 *model.ContestInvite, _a1 error) *InviteService_CreateInvite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InviteService_CreateInvite_Call) RunAndReturn(run func(context.Context, uuid.UUID, *model.CreateInviteRequest, string) (*model.ContestInvite, error)) *InviteService_CreateInvite_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInvite provides a mock function with given fields: ctx, contestID, inviteID, user
func (_m *InviteService) DeleteInvite(ctx context.Context, contestID uuid.UUID, inviteID uuid.UUID, user string) error {
	ret := _m.Called(ctx, contestID, inviteID, user)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInvite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, contestID, inviteID, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InviteService_DeleteInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInvite'
type InviteService_DeleteInvite_Call struct {
	*mock.Call
}

// DeleteInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - inviteID uuid.UUID
//   - user string
func (_e *InviteService_Expecter) DeleteInvite(ctx interface{}, contestID interface{}, inviteID interface{}, user interface{}) *InviteService_DeleteInvite_Call {
	return &InviteService_DeleteInvite_Call{Call: _e.mock.On("DeleteInvite", ctx, contestID, inviteID, user)}
}

func (_c *InviteService_DeleteInvite_Call) Run(run func(ctx context.Context, contestID uuid.UUID, inviteID uuid.UUID, user string)) *InviteService_DeleteInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *InviteService_DeleteInvite_Call) Return(_a0 error) *InviteService_DeleteInvite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InviteService_DeleteInvite_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *InviteService_DeleteInvite_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvitePreview provides a mock function with given fields: ctx, token
func (_m *InviteService) GetInvitePreview(ctx context.Context, token string) (*model.InvitePreviewResponse, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitePreview")
	}

	var r0 *model.InvitePreviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.InvitePreviewResponse, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.InvitePreviewResponse); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.InvitePreviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteService_GetInvitePreview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvitePreview'
type InviteService_GetInvitePreview_Call struct {
	*mock.Call
}

// GetInvitePreview is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *InviteService_Expecter) GetInvitePreview(ctx interface{}, token interface{}) *InviteService_GetInvitePreview_Call {
	return &InviteService_GetInvitePreview_Call{Call: _e.mock.On("GetInvitePreview", ctx, token)}
}

func (_c *InviteService_GetInvitePreview_Call) Run(run func(ctx context.Context, token string)) *InviteService_GetInvitePreview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InviteService_GetInvitePreview_Call) Return(_a0 *model.InvitePreviewResponse, _a1 error) *InviteService_GetInvitePreview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InviteService_GetInvitePreview_Call) RunAndReturn(run func(context.Context, string) (*model.InvitePreviewResponse, error)) *InviteService_GetInvitePreview_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvitesByContestID provides a mock function with given fields: ctx, contestID, user
func (_m *InviteService) GetInvitesByContestID(ctx context.Context, contestID uuid.UUID, user string) ([]model.ContestInvite, error) {
	ret := _m.Called(ctx, contestID, user)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitesByContestID")
	}

	var r0 []model.ContestInvite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]model.ContestInvite, error)); ok {
		return rf(ctx, contestID, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []model.ContestInvite); ok {
		r0 = rf(ctx, contestID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ContestInvite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, contestID, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteService_GetInvitesByContestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvitesByContestID'
type InviteService_GetInvitesByContestID_Call struct {
	*mock.Call
}

// GetInvitesByContestID is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - user string
func (_e *InviteService_Expecter) GetInvitesByContestID(ctx interface{}, contestID interface{}, user interface{}) *InviteService_GetInvitesByContestID_Call {
	return &InviteService_GetInvitesByContestID_Call{Call: _e.mock.On("GetInvitesByContestID", ctx, contestID, user)}
}

func (_c *InviteService_GetInvitesByContestID_Call) Run(run func(ctx context.Context, contestID uuid.UUID, user string)) *InviteService_GetInvitesByContestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *InviteService_GetInvitesByContestID_Call) Return(_a0 []model.ContestInvite, _a1 error) *InviteService_GetInvitesByContestID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InviteService_GetInvitesByContestID_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) ([]model.ContestInvite, error)) *InviteService_GetInvitesByContestID_Call {
	_c.Call.Return(run)
	return _c
}

// RedeemInvite provides a mock function with given fields: ctx, token, user
func (_m *InviteService) RedeemInvite(ctx context.Context, token string, user string) (*model.ContestParticipant, error) {
	ret := _m.Called(ctx, token, user)

	if len(ret) == 0 {
		panic("no return value specified for RedeemInvite")
	}

	var r0 *model.ContestParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.ContestParticipant, error)); ok {
		return rf(ctx, token, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.ContestParticipant); ok {
		r0 = rf(ctx, token, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ContestParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteService_RedeemInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RedeemInvite'
type InviteService_RedeemInvite_Call struct {
	*mock.Call
}

// RedeemInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - user string
func (_e *InviteService_Expecter) RedeemInvite(ctx interface{}, token interface{}, user interface{}) *InviteService_RedeemInvite_Call {
	return &InviteService_RedeemInvite_Call{Call: _e.mock.On("RedeemInvite", ctx, token, user)}
}

func (_c *InviteService_RedeemInvite_Call) Run(run func(ctx context.Context, token string, user string)) *InviteService_RedeemInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *InviteService_RedeemInvite_Call) Return(_a0 *model.ContestParticipant, _a1 error) *InviteService_RedeemInvite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InviteService_RedeemInvite_Call) RunAndReturn(run func(context.Context, string, string) (*model.ContestParticipant, error)) *InviteService_RedeemInvite_Call {
	_c.Call.Return(run)
	return _c
}

// NewInviteService creates a new instance of InviteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteService {
	mock := &InviteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
