// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// LeaderboardService is an autogenerated mock type for the LeaderboardService type
type LeaderboardService struct {
	mock.Mock
}

type LeaderboardService_Expecter struct {
	mock *mock.Mock
}

func (_m *LeaderboardService) EXPECT() *LeaderboardService_Expecter {
	return &LeaderboardService_Expecter{mock: &_m.Mock}
}

// GetLeaderboard provides a mock function with given fields: ctx, limit
func (_m *LeaderboardService) GetLeaderboard(ctx context.Context, limit int) (*model.LeaderboardResponse, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboard")
	}

	var r0 *model.LeaderboardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*model.LeaderboardResponse, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.LeaderboardResponse); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LeaderboardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaderboardService_GetLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboard'
type LeaderboardService_GetLeaderboard_Call struct {
	*mock.Call
}

// GetLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *LeaderboardService_Expecter) GetLeaderboard(ctx interface{}, limit interface{}) *LeaderboardService_GetLeaderboard_Call {
	return &LeaderboardService_GetLeaderboard_Call{Call: _e.mock.On("GetLeaderboard", ctx, limit)}
}

func (_c *LeaderboardService_GetLeaderboard_Call) Run(run func(ctx context.Context, limit int)) *LeaderboardService_GetLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *LeaderboardService_GetLeaderboard_Call) Return(_a0 *model.LeaderboardResponse, _a1 error) *LeaderboardService_GetLeaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LeaderboardService_GetLeaderboard_Call) RunAndReturn(run func(context.Context, int) (*model.LeaderboardResponse, error)) *LeaderboardService_GetLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRank provides a mock function with given fields: ctx, email
func (_m *LeaderboardService) GetUserRank(ctx context.Context, email string) (*model.LeaderboardRankResponse, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRank")
	}

	var r0 *model.LeaderboardRankResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.LeaderboardRankResponse, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.LeaderboardRankResponse); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LeaderboardRankResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaderboardService_GetUserRank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRank'
type LeaderboardService_GetUserRank_Call struct {
	*mock.Call
}

// GetUserRank is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *LeaderboardService_Expecter) GetUserRank(ctx interface{}, email interface{}) *LeaderboardService_GetUserRank_Call {
	return &LeaderboardService_GetUserRank_Call{Call: _e.mock.On("GetUserRank", ctx, email)}
}

func (_c *LeaderboardService_GetUserRank_Call) Run(run func(ctx context.Context, email string)) *LeaderboardService_GetUserRank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *LeaderboardService_GetUserRank_Call) Return(_a0 *model.LeaderboardRankResponse, _a1 error) *LeaderboardService_GetUserRank_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LeaderboardService_GetUserRank_Call) RunAndReturn(run func(context.Context, string) (*model.LeaderboardRankResponse, error)) *LeaderboardService_GetUserRank_Call {
	_c.Call.Return(run)
	return _c
}

// NewLeaderboardService creates a new instance of LeaderboardService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaderboardService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaderboardService {
	mock := &LeaderboardService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
