// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// LeaderboardRepository is an autogenerated mock type for the LeaderboardRepository type
type LeaderboardRepository struct {
	mock.Mock
}

type LeaderboardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LeaderboardRepository) EXPECT() *LeaderboardRepository_Expecter {
	return &LeaderboardRepository_Expecter{mock: &_m.Mock}
}

// GetTopWinners provides a mock function with given fields: ctx, limit
func (_m *LeaderboardRepository) GetTopWinners(ctx context.Context, limit int) ([]model.LeaderboardEntry, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTopWinners")
	}

	var r0 []model.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.LeaderboardEntry, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.LeaderboardEntry); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaderboardRepository_GetTopWinners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopWinners'
type LeaderboardRepository_GetTopWinners_Call struct {
	*mock.Call
}

// GetTopWinners is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *LeaderboardRepository_Expecter) GetTopWinners(ctx interface{}, limit interface{}) *LeaderboardRepository_GetTopWinners_Call {
	return &LeaderboardRepository_GetTopWinners_Call{Call: _e.mock.On("GetTopWinners", ctx, limit)}
}

func (_c *LeaderboardRepository_GetTopWinners_Call) Run(run func(ctx context.Context, limit int)) *LeaderboardRepository_GetTopWinners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *LeaderboardRepository_GetTopWinners_Call) Return(_a0 []model.LeaderboardEntry, _a1 error) *LeaderboardRepository_GetTopWinners_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LeaderboardRepository_GetTopWinners_Call) RunAndReturn(run func(context.Context, int) ([]model.LeaderboardEntry, error)) *LeaderboardRepository_GetTopWinners_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRank provides a mock function with given fields: ctx, email
func (_m *LeaderboardRepository) GetUserRank(ctx context.Context, email string) (*model.LeaderboardRankResponse, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRank")
	}

	var r0 *model.LeaderboardRankResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.LeaderboardRankResponse, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.LeaderboardRankResponse); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LeaderboardRankResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaderboardRepository_GetUserRank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRank'
type LeaderboardRepository_GetUserRank_Call struct {
	*mock.Call
}

// GetUserRank is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *LeaderboardRepository_Expecter) GetUserRank(ctx interface{}, email interface{}) *LeaderboardRepository_GetUserRank_Call {
	return &LeaderboardRepository_GetUserRank_Call{Call: _e.mock.On("GetUserRank", ctx, email)}
}

func (_c *LeaderboardRepository_GetUserRank_Call) Run(run func(ctx context.Context, email string)) *LeaderboardRepository_GetUserRank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *LeaderboardRepository_GetUserRank_Call) Return(_a0 *model.LeaderboardRankResponse, _a1 error) *LeaderboardRepository_GetUserRank_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LeaderboardRepository_GetUserRank_Call) RunAndReturn(run func(context.Context, string) (*model.LeaderboardRankResponse, error)) *LeaderboardRepository_GetUserRank_Call {
	_c.Call.Return(run)
	return _c
}

// NewLeaderboardRepository creates a new instance of LeaderboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaderboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaderboardRepository {
	mock := &LeaderboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
