// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// NatsService is an autogenerated mock type for the NatsService type
type NatsService struct {
	mock.Mock
}

type NatsService_Expecter struct {
	mock *mock.Mock
}

func (_m *NatsService) EXPECT() *NatsService_Expecter {
	return &NatsService_Expecter{mock: &_m.Mock}
}

// PublishContestDeleted provides a mock function with given fields: contestID, updatedBy
func (_m *NatsService) PublishContestDeleted(contestID uuid.UUID, updatedBy string) error {
	ret := _m.Called(contestID, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for PublishContestDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) error); ok {
		r0 = rf(contestID, updatedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NatsService_PublishContestDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishContestDeleted'
type NatsService_PublishContestDeleted_Call struct {
	*mock.Call
}

// PublishContestDeleted is a helper method to define mock.On call
//   - contestID uuid.UUID
//   - updatedBy string
func (_e *NatsService_Expecter) PublishContestDeleted(contestID interface{}, updatedBy interface{}) *NatsService_PublishContestDeleted_Call {
	return &NatsService_PublishContestDeleted_Call{Call: _e.mock.On("PublishContestDeleted", contestID, updatedBy)}
}

func (_c *NatsService_PublishContestDeleted_Call) Run(run func(contestID uuid.UUID, updatedBy string)) *NatsService_PublishContestDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string))
	})
	return _c
}

func (_c *NatsService_PublishContestDeleted_Call) Return(_a0 error) *NatsService_PublishContestDeleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NatsService_PublishContestDeleted_Call) RunAndReturn(run func(uuid.UUID, string) error) *NatsService_PublishContestDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// PublishContestUpdate provides a mock function with given fields: contestID, updatedBy, contest
func (_m *NatsService) PublishContestUpdate(contestID uuid.UUID, updatedBy string, contest *model.Contest) error {
	ret := _m.Called(contestID, updatedBy, contest)

	if len(ret) == 0 {
		panic("no return value specified for PublishContestUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, *model.Contest) error); ok {
		r0 = rf(contestID, updatedBy, contest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NatsService_PublishContestUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishContestUpdate'
type NatsService_PublishContestUpdate_Call struct {
	*mock.Call
}

// PublishContestUpdate is a helper method to define mock.On call
//   - contestID uuid.UUID
//   - updatedBy string
//   - contest *model.Contest
func (_e *NatsService_Expecter) PublishContestUpdate(contestID interface{}, updatedBy interface{}, contest interface{}) *NatsService_PublishContestUpdate_Call {
	return &NatsService_PublishContestUpdate_Call{Call: _e.mock.On("PublishContestUpdate", contestID, updatedBy, contest)}
}

func (_c *NatsService_PublishContestUpdate_Call) Run(run func(contestID uuid.UUID, updatedBy string, contest *model.Contest)) *NatsService_PublishContestUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string), args[2].(*model.Contest))
	})
	return _c
}

func (_c *NatsService_PublishContestUpdate_Call) Return(_a0 error) *NatsService_PublishContestUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NatsService_PublishContestUpdate_Call) RunAndReturn(run func(uuid.UUID, string, *model.Contest) error) *NatsService_PublishContestUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// PublishParticipantAdded provides a mock function with given fields: contestID, participant
func (_m *NatsService) PublishParticipantAdded(contestID uuid.UUID, participant *model.ContestParticipant) error {
	ret := _m.Called(contestID, participant)

	if len(ret) == 0 {
		panic("no return value specified for PublishParticipantAdded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *model.ContestParticipant) error); ok {
		r0 = rf(contestID, participant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NatsService_PublishParticipantAdded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishParticipantAdded'
type NatsService_PublishParticipantAdded_Call struct {
	*mock.Call
}

// PublishParticipantAdded is a helper method to define mock.On call
//   - contestID uuid.UUID
//   - participant *model.ContestParticipant
func (_e *NatsService_Expecter) PublishParticipantAdded(contestID interface{}, participant interface{}) *NatsService_PublishParticipantAdded_Call {
	return &NatsService_PublishParticipantAdded_Call{Call: _e.mock.On("PublishParticipantAdded", contestID, participant)}
}

func (_c *NatsService_PublishParticipantAdded_Call) Run(run func(contestID uuid.UUID, participant *model.ContestParticipant)) *NatsService_PublishParticipantAdded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(*model.ContestParticipant))
	})
	return _c
}

func (_c *NatsService_PublishParticipantAdded_Call) Return(_a0 error) *NatsService_PublishParticipantAdded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NatsService_PublishParticipantAdded_Call) RunAndReturn(run func(uuid.UUID, *model.ContestParticipant) error) *NatsService_PublishParticipantAdded_Call {
	_c.Call.Return(run)
	return _c
}

// PublishParticipantRemoved provides a mock function with given fields: contestID, updatedBy, participant
func (_m *NatsService) PublishParticipantRemoved(contestID uuid.UUID, updatedBy string, participant *model.ContestParticipant) error {
	ret := _m.Called(contestID, updatedBy, participant)

	if len(ret) == 0 {
		panic("no return value specified for PublishParticipantRemoved")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, *model.ContestParticipant) error); ok {
		r0 = rf(contestID, updatedBy, participant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NatsService_PublishParticipantRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishParticipantRemoved'
type NatsService_PublishParticipantRemoved_Call struct {
	*mock.Call
}

// PublishParticipantRemoved is a helper method to define mock.On call
//   - contestID uuid.UUID
//   - updatedBy string
//   - participant *model.ContestParticipant
func (_e *NatsService_Expecter) PublishParticipantRemoved(contestID interface{}, updatedBy interface{}, participant interface{}) *NatsService_PublishParticipantRemoved_Call {
	return &NatsService_PublishParticipantRemoved_Call{Call: _e.mock.On("PublishParticipantRemoved", contestID, updatedBy, participant)}
}

func (_c *NatsService_PublishParticipantRemoved_Call) Run(run func(contestID uuid.UUID, updatedBy string, participant *model.ContestParticipant)) *NatsService_PublishParticipantRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string), args[2].(*model.ContestParticipant))
	})
	return _c
}

func (_c *NatsService_PublishParticipantRemoved_Call) Return(_a0 error) *NatsService_PublishParticipantRemoved_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NatsService_PublishParticipantRemoved_Call) RunAndReturn(run func(uuid.UUID, string, *model.ContestParticipant) error) *NatsService_PublishParticipantRemoved_Call {
	_c.Call.Return(run)
	return _c
}

// PublishQuarterResult provides a mock function with given fields: contestID, updatedBy, quarterResult
func (_m *NatsService) PublishQuarterResult(contestID uuid.UUID, updatedBy string, quarterResult *model.QuarterResult) error {
	ret := _m.Called(contestID, updatedBy, quarterResult)

	if len(ret) == 0 {
		panic("no return value specified for PublishQuarterResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, *model.QuarterResult) error); ok {
		r0 = rf(contestID, updatedBy, quarterResult)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NatsService_PublishQuarterResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishQuarterResult'
type NatsService_PublishQuarterResult_Call struct {
	*mock.Call
}

// PublishQuarterResult is a helper method to define mock.On call
//   - contestID uuid.UUID
//   - updatedBy string
//   - quarterResult *model.QuarterResult
func (_e *NatsService_Expecter) PublishQuarterResult(contestID interface{}, updatedBy interface{}, quarterResult interface{}) *NatsService_PublishQuarterResult_Call {
	return &NatsService_PublishQuarterResult_Call{Call: _e.mock.On("PublishQuarterResult", contestID, updatedBy, quarterResult)}
}

func (_c *NatsService_PublishQuarterResult_Call) Run(run func(contestID uuid.UUID, updatedBy string, quarterResult *model.QuarterResult)) *NatsService_PublishQuarterResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string), args[2].(*model.QuarterResult))
	})
	return _c
}

func (_c *NatsService_PublishQuarterResult_Call) Return(_a0 error) *NatsService_PublishQuarterResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NatsService_PublishQuarterResult_Call) RunAndReturn(run func(uuid.UUID, string, *model.QuarterResult) error) *NatsService_PublishQuarterResult_Call {
	_c.Call.Return(run)
	return _c
}

// PublishSquareUpdate provides a mock function with given fields: contestID, updatedBy, square
func (_m *NatsService) PublishSquareUpdate(contestID uuid.UUID, updatedBy string, square *model.Square) error {
	ret := _m.Called(contestID, updatedBy, square)

	if len(ret) == 0 {
		panic("no return value specified for PublishSquareUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, *model.Square) error); ok {
		r0 = rf(contestID, updatedBy, square)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NatsService_PublishSquareUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishSquareUpdate'
type NatsService_PublishSquareUpdate_Call struct {
	*mock.Call
}

// PublishSquareUpdate is a helper method to define mock.On call
//   - contestID uuid.UUID
//   - updatedBy string
//   - square *model.Square
func (_e *NatsService_Expecter) PublishSquareUpdate(contestID interface{}, updatedBy interface{}, square interface{}) *NatsService_PublishSquareUpdate_Call {
	return &NatsService_PublishSquareUpdate_Call{Call: _e.mock.On("PublishSquareUpdate", contestID, updatedBy, square)}
}

func (_c *NatsService_PublishSquareUpdate_Call) Run(run func(contestID uuid.UUID, updatedBy string, square *model.Square)) *NatsService_PublishSquareUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string), args[2].(*model.Square))
	})
	return _c
}

func (_c *NatsService_PublishSquareUpdate_Call) Return(_a0 error) *NatsService_PublishSquareUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NatsService_PublishSquareUpdate_Call) RunAndReturn(run func(uuid.UUID, string, *model.Square) error) *NatsService_PublishSquareUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewNatsService creates a new instance of NatsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNatsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NatsService {
	mock := &NatsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
