// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	model "github.com/maxmorhardt/squares-api/internal/model"
	service "github.com/maxmorhardt/squares-api/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// ParticipantService is an autogenerated mock type for the ParticipantService type
type ParticipantService struct {
	mock.Mock
}

type ParticipantService_Expecter struct {
	mock *mock.Mock
}

func (_m *ParticipantService) EXPECT() *ParticipantService_Expecter {
	return &ParticipantService_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function with given fields: ctx, contestID, userID, act
func (_m *ParticipantService) Authorize(ctx context.Context, contestID uuid.UUID, userID string, act service.Action) error {
	ret := _m.Called(ctx, contestID, userID, act)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, service.Action) error); ok {
		r0 = rf(ctx, contestID, userID, act)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ParticipantService_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type ParticipantService_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - userID string
//   - act service.Action
func (_e *ParticipantService_Expecter) Authorize(ctx interface{}, contestID interface{}, userID interface{}, act interface{}) *ParticipantService_Authorize_Call {
	return &ParticipantService_Authorize_Call{Call: _e.mock.On("Authorize", ctx, contestID, userID, act)}
}

func (_c *ParticipantService_Authorize_Call) Run(run func(ctx context.Context, contestID uuid.UUID, userID string, act service.Action)) *ParticipantService_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(service.Action))
	})
	return _c
}

func (_c *ParticipantService_Authorize_Call) Return(_a0 error) *ParticipantService_Authorize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ParticipantService_Authorize_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, service.Action) error) *ParticipantService_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// GetMyContests provides a mock function with given fields: ctx, user, search
func (_m *ParticipantService) GetMyContests(ctx context.Context, user string, search string) ([]model.Contest, error) {
	ret := _m.Called(ctx, user, search)

	if len(ret) == 0 {
		panic("no return value specified for GetMyContests")
	}

	var r0 []model.Contest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Contest, error)); ok {
		return rf(ctx, user, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.Contest); ok {
		r0 = rf(ctx, user, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Contest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, user, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParticipantService_GetMyContests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyContests'
type ParticipantService_GetMyContests_Call struct {
	*mock.Call
}

// GetMyContests is a helper method to define mock.On call
//   - ctx context.Context
//   - user string
//   - search string
func (_e *ParticipantService_Expecter) GetMyContests(ctx interface{}, user interface{}, search interface{}) *ParticipantService_GetMyContests_Call {
	return &ParticipantService_GetMyContests_Call{Call: _e.mock.On("GetMyContests", ctx, user, search)}
}

func (_c *ParticipantService_GetMyContests_Call) Run(run func(ctx context.Context, user string, search string)) *ParticipantService_GetMyContests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ParticipantService_GetMyContests_Call) Return(_a0 []model.Contest, _a1 error) *ParticipantService_GetMyContests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParticipantService_GetMyContests_Call) RunAndReturn(run func(context.Context, string, string) ([]model.Contest, error)) *ParticipantService_GetMyContests_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipants provides a mock function with given fields: ctx, contestID, user
func (_m *ParticipantService) GetParticipants(ctx context.Context, contestID uuid.UUID, user string) ([]model.ContestParticipant, error) {
	ret := _m.Called(ctx, contestID, user)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipants")
	}

	var r0 []model.ContestParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]model.ContestParticipant, error)); ok {
		return rf(ctx, contestID, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []model.ContestParticipant); ok {
		r0 = rf(ctx, contestID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ContestParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, contestID, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParticipantService_GetParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipants'
type ParticipantService_GetParticipants_Call struct {
	*mock.Call
}

// GetParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - user string
func (_e *ParticipantService_Expecter) GetParticipants(ctx interface{}, contestID interface{}, user interface{}) *ParticipantService_GetParticipants_Call {
	return &ParticipantService_GetParticipants_Call{Call: _e.mock.On("GetParticipants", ctx, contestID, user)}
}

func (_c *ParticipantService_GetParticipants_Call) Run(run func(ctx context.Context, contestID uuid.UUID, user string)) *ParticipantService_GetParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ParticipantService_GetParticipants_Call) Return(_a0 []model.ContestParticipant, _a1 error) *ParticipantService_GetParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParticipantService_GetParticipants_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) ([]model.ContestParticipant, error)) *ParticipantService_GetParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipantsInternal provides a mock function with given fields: ctx, contestID
func (_m *ParticipantService) GetParticipantsInternal(ctx context.Context, contestID uuid.UUID) ([]model.ContestParticipant, error) {
	ret := _m.Called(ctx, contestID)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipantsInternal")
	}

	var r0 []model.ContestParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ContestParticipant, error)); ok {
		return rf(ctx, contestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.ContestParticipant); ok {
		r0 = rf(ctx, contestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ContestParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, contestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParticipantService_GetParticipantsInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipantsInternal'
type ParticipantService_GetParticipantsInternal_Call struct {
	*mock.Call
}

// GetParticipantsInternal is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
func (_e *ParticipantService_Expecter) GetParticipantsInternal(ctx interface{}, contestID interface{}) *ParticipantService_GetParticipantsInternal_Call {
	return &ParticipantService_GetParticipantsInternal_Call{Call: _e.mock.On("GetParticipantsInternal", ctx, contestID)}
}

func (_c *ParticipantService_GetParticipantsInternal_Call) Run(run func(ctx context.Context, contestID uuid.UUID)) *ParticipantService_GetParticipantsInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ParticipantService_GetParticipantsInternal_Call) Return(_a0 []model.ContestParticipant, _a1 error) *ParticipantService_GetParticipantsInternal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParticipantService_GetParticipantsInternal_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.ContestParticipant, error)) *ParticipantService_GetParticipantsInternal_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveParticipant provides a mock function with given fields: ctx, contestID, targetUserID, user
func (_m *ParticipantService) RemoveParticipant(ctx context.Context, contestID uuid.UUID, targetUserID string, user string) error {
	ret := _m.Called(ctx, contestID, targetUserID, user)

	if len(ret) == 0 {
		panic("no return value specified for RemoveParticipant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = rf(ctx, contestID, targetUserID, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ParticipantService_RemoveParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveParticipant'
type ParticipantService_RemoveParticipant_Call struct {
	*mock.Call
}

// RemoveParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - targetUserID string
//   - user string
func (_e *ParticipantService_Expecter) RemoveParticipant(ctx interface{}, contestID interface{}, targetUserID interface{}, user interface{}) *ParticipantService_RemoveParticipant_Call {
	return &ParticipantService_RemoveParticipant_Call{Call: _e.mock.On("RemoveParticipant", ctx, contestID, targetUserID, user)}
}

func (_c *ParticipantService_RemoveParticipant_Call) Run(run func(ctx context.Context, contestID uuid.UUID, targetUserID string, user string)) *ParticipantService_RemoveParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ParticipantService_RemoveParticipant_Call) Return(_a0 error) *ParticipantService_RemoveParticipant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ParticipantService_RemoveParticipant_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) error) *ParticipantService_RemoveParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateParticipant provides a mock function with given fields: ctx, contestID, targetUserID, req, user
func (_m *ParticipantService) UpdateParticipant(ctx context.Context, contestID uuid.UUID, targetUserID string, req *model.UpdateParticipantRequest, user string) (*model.ContestParticipant, error) {
	ret := _m.Called(ctx, contestID, targetUserID, req, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParticipant")
	}

	var r0 *model.ContestParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *model.UpdateParticipantRequest, string) (*model.ContestParticipant, error)); ok {
		return rf(ctx, contestID, targetUserID, req, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *model.UpdateParticipantRequest, string) *model.ContestParticipant); ok {
		r0 = rf(ctx, contestID, targetUserID, req, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ContestParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, *model.UpdateParticipantRequest, string) error); ok {
		r1 = rf(ctx, contestID, targetUserID, req, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParticipantService_UpdateParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateParticipant'
type ParticipantService_UpdateParticipant_Call struct {
	*mock.Call
}

// UpdateParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - targetUserID string
//   - req *model.UpdateParticipantRequest
//   - user string
func (_e *ParticipantService_Expecter) UpdateParticipant(ctx interface{}, contestID interface{}, targetUserID interface{}, req interface{}, user interface{}) *ParticipantService_UpdateParticipant_Call {
	return &ParticipantService_UpdateParticipant_Call{Call: _e.mock.On("UpdateParticipant", ctx, contestID, targetUserID, req, user)}
}

func (_c *ParticipantService_UpdateParticipant_Call) Run(run func(ctx context.Context, contestID uuid.UUID, targetUserID string, req *model.UpdateParticipantRequest, user string)) *ParticipantService_UpdateParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(*model.UpdateParticipantRequest), args[4].(string))
	})
	return _c
}

func (_c *ParticipantService_UpdateParticipant_Call) Return(_a0 *model.ContestParticipant, _a1 error) *ParticipantService_UpdateParticipant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParticipantService_UpdateParticipant_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, *model.UpdateParticipantRequest, string) (*model.ContestParticipant, error)) *ParticipantService_UpdateParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// NewParticipantService creates a new instance of ParticipantService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParticipantService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParticipantService {
	mock := &ParticipantService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
