// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ParticipantRepository is an autogenerated mock type for the ParticipantRepository type
type ParticipantRepository struct {
	mock.Mock
}

type ParticipantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ParticipantRepository) EXPECT() *ParticipantRepository_Expecter {
	return &ParticipantRepository_Expecter{mock: &_m.Mock}
}

// CountSquaresByUser provides a mock function with given fields: ctx, contestID, userID
func (_m *ParticipantRepository) CountSquaresByUser(ctx context.Context, contestID uuid.UUID, userID string) (int, error) {
	ret := _m.Called(ctx, contestID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountSquaresByUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (int, error)); ok {
		return rf(ctx, contestID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) int); ok {
		r0 = rf(ctx, contestID, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, contestID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParticipantRepository_CountSquaresByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSquaresByUser'
type ParticipantRepository_CountSquaresByUser_Call struct {
	*mock.Call
}

// CountSquaresByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - userID string
func (_e *ParticipantRepository_Expecter) CountSquaresByUser(ctx interface{}, contestID interface{}, userID interface{}) *ParticipantRepository_CountSquaresByUser_Call {
	return &ParticipantRepository_CountSquaresByUser_Call{Call: _e.mock.On("CountSquaresByUser", ctx, contestID, userID)}
}

func (_c *ParticipantRepository_CountSquaresByUser_Call) Run(run func(ctx context.Context, contestID uuid.UUID, userID string)) *ParticipantRepository_CountSquaresByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ParticipantRepository_CountSquaresByUser_Call) Return(_a0 int, _a1 error) *ParticipantRepository_CountSquaresByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParticipantRepository_CountSquaresByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (int, error)) *ParticipantRepository_CountSquaresByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, contestID, userID
func (_m *ParticipantRepository) Delete(ctx context.Context, contestID uuid.UUID, userID string) error {
	ret := _m.Called(ctx, contestID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, contestID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ParticipantRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ParticipantRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - userID string
func (_e *ParticipantRepository_Expecter) Delete(ctx interface{}, contestID interface{}, userID interface{}) *ParticipantRepository_Delete_Call {
	return &ParticipantRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, contestID, userID)}
}

func (_c *ParticipantRepository_Delete_Call) Run(run func(ctx context.Context, contestID uuid.UUID, userID string)) *ParticipantRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ParticipantRepository_Delete_Call) Return(_a0 error) *ParticipantRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ParticipantRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *ParticipantRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByContestID provides a mock function with given fields: ctx, contestID
func (_m *ParticipantRepository) GetAllByContestID(ctx context.Context, contestID uuid.UUID) ([]model.ContestParticipant, error) {
	ret := _m.Called(ctx, contestID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByContestID")
	}

	var r0 []model.ContestParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ContestParticipant, error)); ok {
		return rf(ctx, contestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.ContestParticipant); ok {
		r0 = rf(ctx, contestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ContestParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, contestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParticipantRepository_GetAllByContestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByContestID'
type ParticipantRepository_GetAllByContestID_Call struct {
	*mock.Call
}

// GetAllByContestID is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
func (_e *ParticipantRepository_Expecter) GetAllByContestID(ctx interface{}, contestID interface{}) *ParticipantRepository_GetAllByContestID_Call {
	return &ParticipantRepository_GetAllByContestID_Call{Call: _e.mock.On("GetAllByContestID", ctx, contestID)}
}

func (_c *ParticipantRepository_GetAllByContestID_Call) Run(run func(ctx context.Context, contestID uuid.UUID)) *ParticipantRepository_GetAllByContestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ParticipantRepository_GetAllByContestID_Call) Return(_a0 []model.ContestParticipant, _a1 error) *ParticipantRepository_GetAllByContestID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParticipantRepository_GetAllByContestID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.ContestParticipant, error)) *ParticipantRepository_GetAllByContestID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByContestAndUser provides a mock function with given fields: ctx, contestID, userID
func (_m *ParticipantRepository) GetByContestAndUser(ctx context.Context, contestID uuid.UUID, userID string) (*model.ContestParticipant, error) {
	ret := _m.Called(ctx, contestID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByContestAndUser")
	}

	var r0 *model.ContestParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.ContestParticipant, error)); ok {
		return rf(ctx, contestID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.ContestParticipant); ok {
		r0 = rf(ctx, contestID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ContestParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, contestID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParticipantRepository_GetByContestAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByContestAndUser'
type ParticipantRepository_GetByContestAndUser_Call struct {
	*mock.Call
}

// GetByContestAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
//   - userID string
func (_e *ParticipantRepository_Expecter) GetByContestAndUser(ctx interface{}, contestID interface{}, userID interface{}) *ParticipantRepository_GetByContestAndUser_Call {
	return &ParticipantRepository_GetByContestAndUser_Call{Call: _e.mock.On("GetByContestAndUser", ctx, contestID, userID)}
}

func (_c *ParticipantRepository_GetByContestAndUser_Call) Run(run func(ctx context.Context, contestID uuid.UUID, userID string)) *ParticipantRepository_GetByContestAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ParticipantRepository_GetByContestAndUser_Call) Return(_a0 *model.ContestParticipant, _a1 error) *ParticipantRepository_GetByContestAndUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParticipantRepository_GetByContestAndUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*model.ContestParticipant, error)) *ParticipantRepository_GetByContestAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalAllocatedSquares provides a mock function with given fields: ctx, contestID
func (_m *ParticipantRepository) GetTotalAllocatedSquares(ctx context.Context, contestID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, contestID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalAllocatedSquares")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, contestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, contestID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, contestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParticipantRepository_GetTotalAllocatedSquares_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalAllocatedSquares'
type ParticipantRepository_GetTotalAllocatedSquares_Call struct {
	*mock.Call
}

// GetTotalAllocatedSquares is a helper method to define mock.On call
//   - ctx context.Context
//   - contestID uuid.UUID
func (_e *ParticipantRepository_Expecter) GetTotalAllocatedSquares(ctx interface{}, contestID interface{}) *ParticipantRepository_GetTotalAllocatedSquares_Call {
	return &ParticipantRepository_GetTotalAllocatedSquares_Call{Call: _e.mock.On("GetTotalAllocatedSquares", ctx, contestID)}
}

func (_c *ParticipantRepository_GetTotalAllocatedSquares_Call) Run(run func(ctx context.Context, contestID uuid.UUID)) *ParticipantRepository_GetTotalAllocatedSquares_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ParticipantRepository_GetTotalAllocatedSquares_Call) Return(_a0 int, _a1 error) *ParticipantRepository_GetTotalAllocatedSquares_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParticipantRepository_GetTotalAllocatedSquares_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *ParticipantRepository_GetTotalAllocatedSquares_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, participant
func (_m *ParticipantRepository) Update(ctx context.Context, participant *model.ContestParticipant) error {
	ret := _m.Called(ctx, participant)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ContestParticipant) error); ok {
		r0 = rf(ctx, participant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ParticipantRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ParticipantRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - participant *model.ContestParticipant
func (_e *ParticipantRepository_Expecter) Update(ctx interface{}, participant interface{}) *ParticipantRepository_Update_Call {
	return &ParticipantRepository_Update_Call{Call: _e.mock.On("Update", ctx, participant)}
}

func (_c *ParticipantRepository_Update_Call) Run(run func(ctx context.Context, participant *model.ContestParticipant)) *ParticipantRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.ContestParticipant))
	})
	return _c
}

func (_c *ParticipantRepository_Update_Call) Return(_a0 error) *ParticipantRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ParticipantRepository_Update_Call) RunAndReturn(run func(context.Context, *model.ContestParticipant) error) *ParticipantRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewParticipantRepository creates a new instance of ParticipantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParticipantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParticipantRepository {
	mock := &ParticipantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
