// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// StatsRepository is an autogenerated mock type for the StatsRepository type
type StatsRepository struct {
	mock.Mock
}

type StatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *StatsRepository) EXPECT() *StatsRepository_Expecter {
	return &StatsRepository_Expecter{mock: &_m.Mock}
}

// GetStats provides a mock function with given fields: ctx
func (_m *StatsRepository) GetStats(ctx context.Context) (*model.StatsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *model.StatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.StatsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.StatsResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.StatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatsRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type StatsRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StatsRepository_Expecter) GetStats(ctx interface{}) *StatsRepository_GetStats_Call {
	return &StatsRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *StatsRepository_GetStats_Call) Run(run func(ctx context.Context)) *StatsRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StatsRepository_GetStats_Call) Return(_a0 *model.StatsResponse, _a1 error) *StatsRepository_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatsRepository_GetStats_Call) RunAndReturn(run func(context.Context) (*model.StatsResponse, error)) *StatsRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewStatsRepository creates a new instance of StatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatsRepository {
	mock := &StatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
