// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// DeleteAccount provides a mock function with given fields: ctx, email
func (_m *UserService) DeleteAccount(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserService_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type UserService_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserService_Expecter) DeleteAccount(ctx interface{}, email interface{}) *UserService_DeleteAccount_Call {
	return &UserService_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, email)}
}

func (_c *UserService_DeleteAccount_Call) Run(run func(ctx context.Context, email string)) *UserService_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_DeleteAccount_Call) Return(_a0 error) *UserService_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserService_DeleteAccount_Call) RunAndReturn(run func(context.Context, string) error) *UserService_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveContests provides a mock function with given fields: ctx, email
func (_m *UserService) GetActiveContests(ctx context.Context, email string) ([]model.UserActiveContest, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveContests")
	}

	var r0 []model.UserActiveContest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.UserActiveContest, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.UserActiveContest); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserActiveContest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_GetActiveContests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveContests'
type UserService_GetActiveContests_Call struct {
	*mock.Call
}

// GetActiveContests is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserService_Expecter) GetActiveContests(ctx interface{}, email interface{}) *UserService_GetActiveContests_Call {
	return &UserService_GetActiveContests_Call{Call: _e.mock.On("GetActiveContests", ctx, email)}
}

func (_c *UserService_GetActiveContests_Call) Run(run func(ctx context.Context, email string)) *UserService_GetActiveContests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_GetActiveContests_Call) Return(_a0 []model.UserActiveContest, _a1 error) *UserService_GetActiveContests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_GetActiveContests_Call) RunAndReturn(run func(context.Context, string) ([]model.UserActiveContest, error)) *UserService_GetActiveContests_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: ctx, email, defaultDisplayName
func (_m *UserService) GetProfile(ctx context.Context, email string, defaultDisplayName string) (*model.User, error) {
	ret := _m.Called(ctx, email, defaultDisplayName)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.User, error)); ok {
		return rf(ctx, email, defaultDisplayName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.User); ok {
		r0 = rf(ctx, email, defaultDisplayName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, defaultDisplayName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type UserService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - defaultDisplayName string
func (_e *UserService_Expecter) GetProfile(ctx interface{}, email interface{}, defaultDisplayName interface{}) *UserService_GetProfile_Call {
	return &UserService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, email, defaultDisplayName)}
}

func (_c *UserService_GetProfile_Call) Run(run func(ctx context.Context, email string, defaultDisplayName string)) *UserService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserService_GetProfile_Call) Return(_a0 *model.User, _a1 error) *UserService_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_GetProfile_Call) RunAndReturn(run func(context.Context, string, string) (*model.User, error)) *UserService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx, email
func (_m *UserService) GetStats(ctx context.Context, email string) (*model.UserStatsResponse, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *model.UserStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserStatsResponse, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserStatsResponse); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type UserService_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserService_Expecter) GetStats(ctx interface{}, email interface{}) *UserService_GetStats_Call {
	return &UserService_GetStats_Call{Call: _e.mock.On("GetStats", ctx, email)}
}

func (_c *UserService_GetStats_Call) Run(run func(ctx context.Context, email string)) *UserService_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_GetStats_Call) Return(_a0 *model.UserStatsResponse, _a1 error) *UserService_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_GetStats_Call) RunAndReturn(run func(context.Context, string) (*model.UserStatsResponse, error)) *UserService_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
