// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// GetActiveContests provides a mock function with given fields: ctx, email
func (_m *UserRepository) GetActiveContests(ctx context.Context, email string) ([]model.UserActiveContest, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveContests")
	}

	var r0 []model.UserActiveContest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.UserActiveContest, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.UserActiveContest); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserActiveContest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetActiveContests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveContests'
type UserRepository_GetActiveContests_Call struct {
	*mock.Call
}

// GetActiveContests is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) GetActiveContests(ctx interface{}, email interface{}) *UserRepository_GetActiveContests_Call {
	return &UserRepository_GetActiveContests_Call{Call: _e.mock.On("GetActiveContests", ctx, email)}
}

func (_c *UserRepository_GetActiveContests_Call) Run(run func(ctx context.Context, email string)) *UserRepository_GetActiveContests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetActiveContests_Call) Return(_a0 []model.UserActiveContest, _a1 error) *UserRepository_GetActiveContests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetActiveContests_Call) RunAndReturn(run func(context.Context, string) ([]model.UserActiveContest, error)) *UserRepository_GetActiveContests_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreate provides a mock function with given fields: ctx, email, defaultDisplayName
func (_m *UserRepository) GetOrCreate(ctx context.Context, email string, defaultDisplayName string) (*model.User, error) {
	ret := _m.Called(ctx, email, defaultDisplayName)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.User, error)); ok {
		return rf(ctx, email, defaultDisplayName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.User); ok {
		r0 = rf(ctx, email, defaultDisplayName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, defaultDisplayName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type UserRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - defaultDisplayName string
func (_e *UserRepository_Expecter) GetOrCreate(ctx interface{}, email interface{}, defaultDisplayName interface{}) *UserRepository_GetOrCreate_Call {
	return &UserRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, email, defaultDisplayName)}
}

func (_c *UserRepository_GetOrCreate_Call) Run(run func(ctx context.Context, email string, defaultDisplayName string)) *UserRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_GetOrCreate_Call) Return(_a0 *model.User, _a1 error) *UserRepository_GetOrCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetOrCreate_Call) RunAndReturn(run func(context.Context, string, string) (*model.User, error)) *UserRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx, email
func (_m *UserRepository) GetStats(ctx context.Context, email string) (*model.UserStatsResponse, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *model.UserStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserStatsResponse, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserStatsResponse); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type UserRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) GetStats(ctx interface{}, email interface{}) *UserRepository_GetStats_Call {
	return &UserRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, email)}
}

func (_c *UserRepository_GetStats_Call) Run(run func(ctx context.Context, email string)) *UserRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetStats_Call) Return(_a0 *model.UserStatsResponse, _a1 error) *UserRepository_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetStats_Call) RunAndReturn(run func(context.Context, string) (*model.UserStatsResponse, error)) *UserRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// ScrubUserData provides a mock function with given fields: ctx, email
func (_m *UserRepository) ScrubUserData(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ScrubUserData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_ScrubUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScrubUserData'
type UserRepository_ScrubUserData_Call struct {
	*mock.Call
}

// ScrubUserData is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) ScrubUserData(ctx interface{}, email interface{}) *UserRepository_ScrubUserData_Call {
	return &UserRepository_ScrubUserData_Call{Call: _e.mock.On("ScrubUserData", ctx, email)}
}

func (_c *UserRepository_ScrubUserData_Call) Run(run func(ctx context.Context, email string)) *UserRepository_ScrubUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_ScrubUserData_Call) Return(_a0 error) *UserRepository_ScrubUserData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_ScrubUserData_Call) RunAndReturn(run func(context.Context, string) error) *UserRepository_ScrubUserData_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
