// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// GetActiveContests provides a mock function with given fields: ctx, email
func (_m *UserRepository) GetActiveContests(ctx context.Context, email string) ([]model.UserActiveContest, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveContests")
	}

	var r0 []model.UserActiveContest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.UserActiveContest, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.UserActiveContest); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserActiveContest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetActiveContests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveContests'
type UserRepository_GetActiveContests_Call struct {
	*mock.Call
}

// GetActiveContests is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) GetActiveContests(ctx interface{}, email interface{}) *UserRepository_GetActiveContests_Call {
	return &UserRepository_GetActiveContests_Call{Call: _e.mock.On("GetActiveContests", ctx, email)}
}

func (_c *UserRepository_GetActiveContests_Call) Run(run func(ctx context.Context, email string)) *UserRepository_GetActiveContests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetActiveContests_Call) Return(_a0 []model.UserActiveContest, _a1 error) *UserRepository_GetActiveContests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetActiveContests_Call) RunAndReturn(run func(context.Context, string) ([]model.UserActiveContest, error)) *UserRepository_GetActiveContests_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepository) GetByEmail(ctx context.Context, email string) (*model.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserRepository_GetByEmail_Call {
	return &UserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetByEmail_Call) Return(_a0 *model.User, _a1 error) *UserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *UserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreate provides a mock function with given fields: ctx, email, defaultDisplayName, defaultInitials
func (_m *UserRepository) GetOrCreate(ctx context.Context, email string, defaultDisplayName string, defaultInitials string) (*model.User, error) {
	ret := _m.Called(ctx, email, defaultDisplayName, defaultInitials)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.User, error)); ok {
		return rf(ctx, email, defaultDisplayName, defaultInitials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.User); ok {
		r0 = rf(ctx, email, defaultDisplayName, defaultInitials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, defaultDisplayName, defaultInitials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type UserRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - defaultDisplayName string
//   - defaultInitials string
func (_e *UserRepository_Expecter) GetOrCreate(ctx interface{}, email interface{}, defaultDisplayName interface{}, defaultInitials interface{}) *UserRepository_GetOrCreate_Call {
	return &UserRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, email, defaultDisplayName, defaultInitials)}
}

func (_c *UserRepository_GetOrCreate_Call) Run(run func(ctx context.Context, email string, defaultDisplayName string, defaultInitials string)) *UserRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *UserRepository_GetOrCreate_Call) Return(_a0 *model.User, _a1 error) *UserRepository_GetOrCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetOrCreate_Call) RunAndReturn(run func(context.Context, string, string, string) (*model.User, error)) *UserRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx, email
func (_m *UserRepository) GetStats(ctx context.Context, email string) (*model.UserStatsResponse, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *model.UserStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserStatsResponse, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserStatsResponse); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type UserRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) GetStats(ctx interface{}, email interface{}) *UserRepository_GetStats_Call {
	return &UserRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, email)}
}

func (_c *UserRepository_GetStats_Call) Run(run func(ctx context.Context, email string)) *UserRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetStats_Call) Return(_a0 *model.UserStatsResponse, _a1 error) *UserRepository_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetStats_Call) RunAndReturn(run func(context.Context, string) (*model.UserStatsResponse, error)) *UserRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenRevoked provides a mock function with given fields: ctx, email, issuedAtUnix
func (_m *UserRepository) IsTokenRevoked(ctx context.Context, email string, issuedAtUnix int64) (bool, error) {
	ret := _m.Called(ctx, email, issuedAtUnix)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenRevoked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (bool, error)); ok {
		return rf(ctx, email, issuedAtUnix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) bool); ok {
		r0 = rf(ctx, email, issuedAtUnix)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, email, issuedAtUnix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_IsTokenRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenRevoked'
type UserRepository_IsTokenRevoked_Call struct {
	*mock.Call
}

// IsTokenRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - issuedAtUnix int64
func (_e *UserRepository_Expecter) IsTokenRevoked(ctx interface{}, email interface{}, issuedAtUnix interface{}) *UserRepository_IsTokenRevoked_Call {
	return &UserRepository_IsTokenRevoked_Call{Call: _e.mock.On("IsTokenRevoked", ctx, email, issuedAtUnix)}
}

func (_c *UserRepository_IsTokenRevoked_Call) Run(run func(ctx context.Context, email string, issuedAtUnix int64)) *UserRepository_IsTokenRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *UserRepository_IsTokenRevoked_Call) Return(_a0 bool, _a1 error) *UserRepository_IsTokenRevoked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_IsTokenRevoked_Call) RunAndReturn(run func(context.Context, string, int64) (bool, error)) *UserRepository_IsTokenRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// ScrubUserData provides a mock function with given fields: ctx, email
func (_m *UserRepository) ScrubUserData(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ScrubUserData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_ScrubUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScrubUserData'
type UserRepository_ScrubUserData_Call struct {
	*mock.Call
}

// ScrubUserData is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) ScrubUserData(ctx interface{}, email interface{}) *UserRepository_ScrubUserData_Call {
	return &UserRepository_ScrubUserData_Call{Call: _e.mock.On("ScrubUserData", ctx, email)}
}

func (_c *UserRepository_ScrubUserData_Call) Run(run func(ctx context.Context, email string)) *UserRepository_ScrubUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_ScrubUserData_Call) Return(_a0 error) *UserRepository_ScrubUserData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_ScrubUserData_Call) RunAndReturn(run func(context.Context, string) error) *UserRepository_ScrubUserData_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, email, initials
func (_m *UserRepository) UpdateProfile(ctx context.Context, email string, initials string) (*model.User, []model.Square, error) {
	ret := _m.Called(ctx, email, initials)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *model.User
	var r1 []model.Square
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.User, []model.Square, error)); ok {
		return rf(ctx, email, initials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.User); ok {
		r0 = rf(ctx, email, initials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) []model.Square); ok {
		r1 = rf(ctx, email, initials)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]model.Square)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, initials)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserRepository_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type UserRepository_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - initials string
func (_e *UserRepository_Expecter) UpdateProfile(ctx interface{}, email interface{}, initials interface{}) *UserRepository_UpdateProfile_Call {
	return &UserRepository_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, email, initials)}
}

func (_c *UserRepository_UpdateProfile_Call) Run(run func(ctx context.Context, email string, initials string)) *UserRepository_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_UpdateProfile_Call) Return(_a0 *model.User, _a1 []model.Square, _a2 error) *UserRepository_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UserRepository_UpdateProfile_Call) RunAndReturn(run func(context.Context, string, string) (*model.User, []model.Square, error)) *UserRepository_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
