// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maxmorhardt/squares-api/internal/model"
	mock "github.com/stretchr/testify/mock"

	websocket "github.com/gorilla/websocket"
)

// WebSocketService is an autogenerated mock type for the WebSocketService type
type WebSocketService struct {
	mock.Mock
}

type WebSocketService_Expecter struct {
	mock *mock.Mock
}

func (_m *WebSocketService) EXPECT() *WebSocketService_Expecter {
	return &WebSocketService_Expecter{mock: &_m.Mock}
}

// HandleWebSocketConnection provides a mock function with given fields: ctx, contest, participants, conn
func (_m *WebSocketService) HandleWebSocketConnection(ctx context.Context, contest *model.Contest, participants []model.ContestParticipant, conn *websocket.Conn) {
	_m.Called(ctx, contest, participants, conn)
}

// WebSocketService_HandleWebSocketConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleWebSocketConnection'
type WebSocketService_HandleWebSocketConnection_Call struct {
	*mock.Call
}

// HandleWebSocketConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - contest *model.Contest
//   - participants []model.ContestParticipant
//   - conn *websocket.Conn
func (_e *WebSocketService_Expecter) HandleWebSocketConnection(ctx interface{}, contest interface{}, participants interface{}, conn interface{}) *WebSocketService_HandleWebSocketConnection_Call {
	return &WebSocketService_HandleWebSocketConnection_Call{Call: _e.mock.On("HandleWebSocketConnection", ctx, contest, participants, conn)}
}

func (_c *WebSocketService_HandleWebSocketConnection_Call) Run(run func(ctx context.Context, contest *model.Contest, participants []model.ContestParticipant, conn *websocket.Conn)) *WebSocketService_HandleWebSocketConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Contest), args[2].([]model.ContestParticipant), args[3].(*websocket.Conn))
	})
	return _c
}

func (_c *WebSocketService_HandleWebSocketConnection_Call) Return() *WebSocketService_HandleWebSocketConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *WebSocketService_HandleWebSocketConnection_Call) RunAndReturn(run func(context.Context, *model.Contest, []model.ContestParticipant, *websocket.Conn)) *WebSocketService_HandleWebSocketConnection_Call {
	_c.Run(run)
	return _c
}

// NewWebSocketService creates a new instance of WebSocketService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebSocketService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebSocketService {
	mock := &WebSocketService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
