profile: coverage.out
threshold:
  file: 0
  package: 0
  total: 32

exclude:
  paths:
    - cmd
    - docs
    - internal/bootstrap
    - internal/config
    - internal/errs
    - internal/metrics
    - internal/middleware
    - internal/model
    - internal/repository
    - internal/routes
    - internal/templates
