name: PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  pr-title:
    uses: maxmorhardt/workflows/.github/workflows/pr-title.yml@main
